# Generated by Django 6.0 on 2026-01-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_financetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=15)),
                ('product_issue', models.CharField(max_length=255)),
                ('product_with', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('product_status', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('SCRAP', 'Scrap')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.DeleteModel(
            name='FinanceTransaction',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
