# Generated by Django 6.0 on 2026-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_entry_delete_financetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
