# Generated by Django 6.0 on 2026-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
