# Generated by Django 6.0 on 2026-01-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Finance',
            },
        ),
    ]
