# Generated by Django 6.0 on 2026-01-11 07:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=120)),
                ('mobile_num', models.CharField(max_length=15)),
                ('particulars', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Quotations',
            },
        ),
    ]
