# Generated by Django 6.0 on 2026-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
