# Generated by Django 6.0 on 2026-01-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
