# Generated by Django 6.0 on 2026-01-12 00:20

from django.db import migrations, models

ALLOWED = {"DAILY_CHARGES", "STOCK_IN_LOCAL", "SERVICE_IN_LOCAL", "OTHER"}


def forwards(apps, schema_editor):
    Finance = apps.get_model('management', 'Finance')
    for obj in Finance.objects.all():
        if obj.reason not in ALLOWED:
            obj.reason = 'OTHER'
            obj.save(update_fields=['reason'])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_entry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='reason',
            field=models.CharField(
                max_length=255,
                choices=[
                    ('DAILY_CHARGES', 'Daily Charges'),
                    ('STOCK_IN_LOCAL', 'Stock In Local'),
                    ('SERVICE_IN_LOCAL', 'Service In Local'),
                    ('OTHER', 'Other')
                ],
                default='OTHER'
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
