# Generated by Django 6.0 on 2026-01-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_finance_reason_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_json',
            field=models.TextField(default='[]', help_text='JSON array of line items'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
