# Generated by Django 6.0 on 2026-01-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_invoice_particulars_remove_invoice_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_json',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
