# Generated by Django 6.0 on 2026-01-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_invoiceitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='stock',
        ),
    ]
