# Generated by Django 6.0 on 2026-01-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_invoiceitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='management.stock'),
        ),
    ]
