# Generated by Django 6.0 on 2026-01-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auditevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
    ]
