# Generated by Django 6.0 on 2026-02-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_auditevent_options'),
        ('management', '0022_stock_sale_cost_price'),
    ]

    operations = [
    ]
