# Generated by Django 6.0 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_merge_20260216_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile_num', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
