# Generated by Django 6.0 on 2026-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_stock_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='reason',
            field=models.CharField(choices=[('SHOP_MAINTENANCE', 'Shop maintenance'), ('LOCAL_SERVICE', 'Local service'), ('BY_ORDER_FROM_DEALER', 'By order from dealer'), ('STOCK_FROM_LOCAL', 'Stock from local'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
